"""Repository port interfaces.

These Protocol classes define the contract that all database adapters must implement.
Services depend on these ports — never on concrete adapter implementations.
"""

from typing import Protocol
from uuid import UUID

from poolmaster_shared.domain.contest import Contest
from poolmaster_shared.domain.draft import DraftPick, DraftSession
from poolmaster_shared.domain.league import League, LeagueMembership
from poolmaster_shared.domain.team import Team, TeamRoster
from poolmaster_shared.domain.tenant import Tenant
from poolmaster_shared.domain.user import User


class TenantRepository(Protocol):
    async def find_by_id(self, id: UUID) -> Tenant | None: ...
    async def find_by_slug(self, slug: str) -> Tenant | None: ...
    async def create(self, tenant: Tenant) -> Tenant: ...
    async def update(self, id: UUID, updates: dict) -> Tenant: ...


class UserRepository(Protocol):
    async def find_by_id(self, id: UUID, tenant_id: UUID) -> User | None: ...
    async def find_by_email(self, email: str) -> User | None: ...
    async def find_by_tenant(self, tenant_id: UUID) -> list[User]: ...
    async def create(self, user: User) -> User: ...
    async def update(self, id: UUID, updates: dict) -> User: ...
    async def delete(self, id: UUID) -> None: ...


class LeagueRepository(Protocol):
    async def find_by_id(self, id: UUID, tenant_id: UUID) -> League | None: ...
    async def find_by_tenant(self, tenant_id: UUID) -> list[League]: ...
    async def create(self, league: League) -> League: ...
    async def update(self, id: UUID, updates: dict) -> League: ...
    async def delete(self, id: UUID) -> None: ...


class LeagueMembershipRepository(Protocol):
    async def find_by_league(self, league_id: UUID) -> list[LeagueMembership]: ...
    async def find_by_user(self, user_id: UUID) -> list[LeagueMembership]: ...
    async def create(self, membership: LeagueMembership) -> LeagueMembership: ...
    async def update(self, id: UUID, updates: dict) -> LeagueMembership: ...
    async def delete(self, id: UUID) -> None: ...


class ContestRepository(Protocol):
    async def find_by_id(self, id: UUID, tenant_id: UUID) -> Contest | None: ...
    async def find_by_league(self, league_id: UUID) -> list[Contest]: ...
    async def create(self, contest: Contest) -> Contest: ...
    async def update(self, id: UUID, updates: dict) -> Contest: ...
    async def delete(self, id: UUID) -> None: ...


class TeamRepository(Protocol):
    async def find_by_id(self, id: UUID) -> Team | None: ...
    async def find_by_contest(self, contest_id: UUID) -> list[Team]: ...
    async def create(self, team: Team) -> Team: ...
    async def get_roster(self, team_id: UUID) -> list[TeamRoster]: ...
    async def add_to_roster(self, roster_entry: TeamRoster) -> TeamRoster: ...


class DraftSessionRepository(Protocol):
    async def find_by_id(self, id: UUID) -> DraftSession | None: ...
    async def find_by_contest(self, contest_id: UUID) -> DraftSession | None: ...
    async def create(self, session: DraftSession) -> DraftSession: ...
    async def update(self, id: UUID, updates: dict) -> DraftSession: ...
    async def get_picks(self, session_id: UUID) -> list[DraftPick]: ...
    async def add_pick(self, pick: DraftPick) -> DraftPick: ...
