CREATE TYPE "PrismaLeagueIconKey" AS ENUM (
  'GOLF_FLAG',
  'GOLF_BALL',
  'FOOTBALL',
  'FOOTBALL_HELMET',
  'BASKETBALL',
  'BASKETBALL_HOOP',
  'CHECKERED_FLAG',
  'RACING_WHEEL',
  'TENNIS_BALL',
  'TENNIS_RACKET',
  'HORSESHOE',
  'SOCCER_BALL',
  'HOCKEY_STICK',
  'HOCKEY_PUCK',
  'BASEBALL',
  'BASEBALL_BAT',
  'FIGHT_GLOVE',
  'TROPHY',
  'WHISTLE',
  'STOPWATCH'
);

ALTER TABLE "leagues"
ADD COLUMN "icon_key" "PrismaLeagueIconKey" NOT NULL DEFAULT 'TROPHY';
